Pin npm versions

diff --git a/json/Dockerfile b/json/Dockerfile
--- a/json/Dockerfile
+++ b/json/Dockerfile
@@ -9,7 +9,7 @@ ARG USER_HOME=/home/default
 ARG USER_ID=1000
 ARG USER_GECOS=Default
 
-# hadolint ignore=DL3016,DL3018
+# hadolint ignore=DL3018
 RUN apk --update --no-cache add \
     jose \
     jq \
@@ -17,10 +17,7 @@ RUN apk --update --no-cache add \
     openssl \
     py3-setuptools \
     py3-pip \
-    && rm -rf /var/cache/apk/* \
-    && npm install -g jsonlint \
-    && npm install -g prettyjson \
-    && npm install -g jwt-cli
+    && rm -rf /var/cache/apk/*
 
 SHELL ["/bin/ash", "-eo", "pipefail", "-c"]
 
@@ -28,6 +25,16 @@ RUN pip3 install --no-cache-dir --upgrade --break-system-packages \
     json2yaml==1.2.0 \
     PyJWT==2.10.1 \
     && msg="$(pip list --outdated | grep -i -e json2yaml -e PyJWT || true)" \
+    && if [ -n "${msg}" ]; then \
+       >&2 echo "ERROR: outdated: ${msg}" ; \
+       exit 1 ; \
+    fi
+
+RUN npm install -g \
+    jsonlint@1.6.3 \
+    jwt-cli@2.0.0 \
+    prettyjson@1.2.5 \
+    && msg="$(npm outdated --global | grep -i -e jsonlint -e jwt-cli -e prettyjson || true)" \
     && if [ -n "${msg}" ]; then \
        >&2 echo "ERROR: outdated: ${msg}" ; \
        exit 1 ; \
